### ISSUE TITLE
Inconsistency in nullness documentation

### ISSUE THREAD

**Issue by mernst** [liflab/beepbeep-3#57]
EventTracker declares

```java
  public /*@ non_null @*/ ProvenanceNode getProvenanceTree(int proc_id, int stream_index,
      int stream_pos);
```
but its subclass ApplyFunction.ShiftTracker contains
```java
    @Override
    public ProvenanceNode getProvenanceTree(int proc_id, int stream_index, int stream_pos)
    {
      return null;
    }
```

Is the `EventTracker` documentation incorrect, or is the `ApplyFunction.ShiftTracker` implementation incorrect?

**Comment by sylvainhalle** [comment]
This part of the implementation (the whole "event tracking" thing) works but is a bit flaky and should be restructured (I am working on this on a part-time basis). What happens here is that `ShiftTracker` is a special tracker whose method `getProvenanceTree` is never intended to be called. So I suppose for the moment that returning an `UnknownNode` in order to satisfy the declaration should be fine.

**Comment by mernst** [comment]
If the method is never intended to be called, then another possible design would be for its body to throw an exception rather than returning a value.  That would immediately indicate that the call is invalid.
